services:
  db:
    image: pgvector/pgvector:pg18
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flomingo
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
